apiVersion: v1
kind: ServiceAccount
metadata:
  name: ftp-server-sa
  namespace: ftp
  annotations:
    tke.cloud.tencent.com/role-arn: "qcs::cam::uin/REPLACE_ME:roleName/COSFTPRole"
    tke.cloud.tencent.com/audience: "sts.cloud.tencent.com"
    tke.cloud.tencent.com/token-expiration: "3600"