apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: ftp-public
  namespace: ftp
spec:
  parentRefs:
    - name: public-gateway
      sectionName: ftp-control
  rules:
    - backendRefs:
        - name: ftp-server
          port: 2121
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: ftp-passive-50000
  namespace: ftp
spec:
  parentRefs:
    - name: public-gateway
      sectionName: ftp-passive-50000
  rules:
    - backendRefs:
        - name: ftp-server
          port: 50000
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ftp-proxy-protocol
  namespace: ftp
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: TCPRoute
      name: ftp-public
    - group: gateway.networking.k8s.io
      kind: TCPRoute
      name: ftp-passive-50000
  proxyProtocol:
    version: v2